# Install pre-commit hooks via
# pre-commit install
exclude: >
  (?x)^(
    tests/.*\.xml|
    tests/.*\.myst|
    tests/.*\.tex|
    tests/.*\_build
  )$

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      additional_dependencies:
      - flake8-bugbear~=23.12.2
      - flake8-comprehensions~=3.14.0
      - pep8-naming~=0.13.3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.941
    hooks:
    - id: mypy
      additional_dependencies: [types-all]
      args: [--no-strict-optional, --ignore-missing-imports]
      exclude: tests/roots/.*py

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.11.0
    hooks:
    - id: pretty-format-toml
      args: [--autofix]
