# Install pre-commit hooks via
# pre-commit install
exclude: >
  (?x)^(
    tests/.*\.xml|
    tests/.*\.myst|
    tests/.*\.tex|
    tests/.*\_build
  )$

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.46"
    hooks:
    - id: check-manifest
      args: [--no-build-isolation]
      additional_dependencies: [setuptools>=46.4.0]

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      additional_dependencies:
      - flake8-bugbear~=21.3.1
      - flake8-comprehensions~=3.4.0
      - pep8-naming~=0.11.1

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    - id: mypy
      additional_dependencies: ["sphinx>=3,<4"]
      exclude: tests/roots/.*py

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.16.0
    hooks:
    - id: setup-cfg-fmt
